#!/bin/bash

#############
# FUNCTIONS #
#############

# --------------------------------------------------------
# Function for creating log entries on the console
# --------------------------------------------------------
# $1 - Log level
# $2 - Log text
# --------------------------------------------------------
function log() {

    # read parameters
    local level="$1"
    local text="$2"

    # create log message
    local now=$(date +"%d-%m-%Y %H:%M:%S")
    echo -e "\n$now [$level] $text\n"
}

# ---------------------------------------------------------------
# Function for printing the usage of this script
# ---------------------------------------------------------------
function usage() {

    # print help text
    cat <<USAGE
Usage:
  $scriptName [Options] <Args>
Required options:
  -u <username>         Username of the nexus repository manager server
  -p <password>         Password of the nexus repository manager server
  -f <folder path>      Path of the local folder to upload
  -n <nexus url>        URL of the nexus repository manager server
  -r <repo name>        Name of the repository to upload the files
  -h                    Show this help text
Example:
  $scriptName -u my-username -p my-password -f /my/folder/path/to/upload -n http://my-nexus-url:8081 -r my-repo-name
USAGE

    # exit with error
    exit -1
}


##########
# SCRIPT #
##########

# echo script banner
echo ""
echo "####################################"
echo "# Nexus Repository Folder Uploader #"
echo "####################################"
echo ""

# get script folder
scriptPath="$(readlink -f $0)"
scriptFolder="$(dirname $scriptPath)"
scriptName="$(basename $scriptPath)"

# get command line args
while getopts u:p:f:n:r:h opt
do
    case $opt in
        u)
            username="$OPTARG"
        ;;
        p)
            password="$OPTARG"
        ;;
        f)
            folderPath="$OPTARG"
        ;;
        n)
            nexusUrl="$OPTARG"
        ;;
        r)
            repositoryName="$OPTARG"
        ;;
        h)
            usage
            exit -1
        ;;
        \?)
            log "ERROR" "Invalid option: -$OPTARG"
            exit -1
        ;;
    esac
done

if ([ "$username" == "" ] || [ "$password" == "" ] || [ "$folderPath" == "" ] || [ "$nexusUrl" == "" ] || [ "$repositoryName" == "" ])
then
    # print usage
    usage
fi

find "$folderPath" -name '*' | while read filePath
do 
    # get file name
    fileName=$(basename $filePath)

    # get relative path to file
    relativePath="$(echo $filePath | sed -r "s|$folderPath||g")"

    # get upload url
    nexusUploadUrl="$nexusUrl/repository/${repositoryName}${relativePath}"

    # upload file to nexus repository manager server
    log "info" "Upload file '$fileName' to URL '$nexusUploadUrl'"
    curl -u "$username:$password" --upload-file "$filePath" "$nexusUploadUrl"
done